### ISSUE TITLE
Skill in outfit frame 

### ISSUE THREAD

**Issue by Aergernis** [Wuild/FishMaster#10]
When opening the outfit frame, the fishng skill is only updating when hovering over an equiped item.

**Comment by Wuild** [comment]
i'm unable to reproduce this.

**Comment by Aergernis** [comment]
okay, when i disable every other addon it's not happenign anymore. But then also the equipped fishingrod is not show after restarting the game. only the tooltip will apear, but it dosen't change the "skill bar"

I'm going to test what addon is causing this problem

**Comment by Aergernis** [comment]
Enchantrix is causing this problem. When it's activated and i hover above the weaponslot (eqipped with the fihingrod), the skill bar will fill to the actual fishing skill.

**Comment by Wuild** [comment]
About the icon not showing, that i know of. I just havnt found why and how to fix it yet.

**Comment by Aergernis** [comment]
1.06 is working.  Do you want to leave debugging in there? If not i'll not translate it.

**Comment by Wuild** [comment]
yes debugging is there to stay
