### ISSUE TITLE
Fishmaster is calling secure function

### ISSUE THREAD

**Issue by Aergernis** [Wuild/FishMaster#11]
Fishmaster is calling a secure function

`1x [ADDON_ACTION_BLOCKED] AddOn 'FishMaster' hat versucht die geschützte Funktion 'FishMaster_ToolbarCast:SetAttribute()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetAttribute'
FishMaster\scripts/toolbar.lua:60: in function `ToolbarCast'
FishMaster\scripts/toolbar.lua:10: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>`

**Comment by Wuild** [comment]
Done
