### ISSUE TITLE
Lua Error in scripts/tracker.lua

### ISSUE THREAD

**Issue by Aergernis** [Wuild/FishMaster#8]
`97x FishMaster\scripts/tracker.lua:114: attempt to compare number with nil
FishMaster\scripts/tracker.lua:114: in function `SetInfo'
FishMaster\scripts/tracker.lua:48: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
sName = nil
sRank = nil
numTempPoints = nil
sMaxRank = nil
skillModifier = nil
sDescription = nil
(*temporary) = 1
(*temporary) = 28
(*temporary) = "Sprache: Trollisch"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 300
(*temporary) = 0
(*temporary) = 0
(*temporary) = 300
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
`

**Comment by Wuild** [comment]
This has been fixed no?

**Comment by Aergernis** [comment]
sems to be fixed. at leastr for me. thanks.
