### ISSUE TITLE
Lua error scripts/equipment/ItemSlot.lua

### ISSUE THREAD

**Issue by Aergernis** [Wuild/FishMaster#9]
When clicking on a Slot in Outfit frame i get this error

`29x ...aceFishMaster\scripts/equipment/ItemSlot.lua:100: bad argument #1 to 'ipairs' (table expected, got nil)
[C]: in function `ipairs'
...aceFishMaster\scripts/equipment/ItemSlot.lua:100: in function `OnReceiveDrag'
...aceFishMaster\scripts/equipment/ItemSlot.lua:39: in function `OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1`

**Comment by Wuild** [comment]
Fixed
